#!/usr/bin/env python3

import rospy
from geometry_msgs.msg import Twist

import mardan.hardware.i2c as i2c


class MotorController:
    def __init__(self):
        self.sub = rospy.Subscriber("motors/motor_twist", Twist, self.callback)
        self.vel_max = 200
        i2c.init_i2c_bus()

    def callback(self, twist):
        l_val = int((twist.linear.x - twist.angular.z)*self.vel_max/2)
        r_val = int((twist.linear.x + twist.angular.z)*self.vel_max/2)
        i2c.send_speed(l_val, r_val)


def main():
    rospy.init_node('motor_control')
    obc = MotorController()
    try:
        rospy.spin()
    except KeyboardInterrupt:
        print("Shutting down")


if __name__ == '__main__':
    main()
