name: docker_build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    base_image:
        name: Build base container
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
        env:
          IMAGE_NAME: mardan_base_noetic
        outputs:
          # used to propagate the name of the image (e.g. ghcr.io/roboticamed/mardan/mardan_base_noetic:latest) to the dependant jobs
          image_name: ${{ steps.calculate_image_name.outputs.image_name }}
        steps:
          - id: checkout
            uses: actions/checkout@v3
          - id: setup_qemu
            uses: docker/setup-qemu-action@v2
            with:
              platforms: "arm64"
          - id: setup_buildx
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          - id: login
            name: Log in to registry
            run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          - id: calculate_image_name
            name: Calculate image name
            run: |
              IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
              IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
              VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
              [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
              [ "$VERSION" == "main" ] && VERSION=latest
              echo IMAGE_ID=$IMAGE_ID
              echo VERSION=$VERSION
              echo "image_name=$IMAGE_ID:$VERSION" >> "$GITHUB_OUTPUT"
          - id: build
            name: Build and push
            run: >
              docker buildx build
              --push
              --file src/ros/mardan/docker/$IMAGE_NAME.dockerfile
              --platform linux/amd64,linux/arm64
              --tag ${{ steps.calculate_image_name.outputs.image_name }}
              --label "runnumber=${GITHUB_RUN_ID}"
              .
    
    runtime_image:
      name: Build runtime container
      runs-on: ubuntu-latest
      needs:
        - base_image
      permissions:
          packages: write
          contents: read
      env:
        IMAGE_NAME: mardan_noetic
        BASE_IMAGE: ${{ needs.base_image.outputs.image_name }}
      outputs:
          # used to propagate the name of the image (e.g. ghcr.io/roboticamed/mardan/mardan_base_noetic:latest) to the dependant jobs
          image_name: ${{ steps.calculate_image_name.outputs.image_name }}
      steps:
        - id: checkout
          name: Checkout
          uses: actions/checkout@v3
        - id: setup_qemu
          uses: docker/setup-qemu-action@v2
          with:
            platforms: "arm64"
        - id: setup_buildx
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - id: login
          name: Log in to registry
          run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
        - id: calculate_image_name
          name: Calculate image name
          run: |
            IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
            IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
            VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
            [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
            [ "$VERSION" == "main" ] && VERSION=latest
            echo IMAGE_ID=$IMAGE_ID
            echo VERSION=$VERSION
            echo "image_name=$IMAGE_ID:$VERSION" >> "$GITHUB_OUTPUT"
        - id: build
          name: Build and push
          run: >
            docker buildx build
            --push
            --build-arg="BASE_IMAGE=$BASE_IMAGE"
            --file src/ros/mardan/docker/$IMAGE_NAME.dockerfile
            --platform linux/amd64,linux/arm64
            --tag ${{ steps.calculate_image_name.outputs.image_name }}
            --label "runnumber=${GITHUB_RUN_ID}"
            .
