name: main

on: [push]

jobs:
    build:
        name: Build base container
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Run a one-line script
            run: |
              echo Hello, world!
